services:
  - type: web
    name: loja-utilidades-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://loja-utilidades.vercel.app,https://frontend-dun-omega-57.vercel.app

databases:
  - name: loja-utilidades-db
    databaseName: loja_utilidades
    user: loja_user
